/* Loads v2 ES modules for testing.

   Two traps this helper exists to avoid:

   1. ESM module caching. `import()` returns the SAME module instance for
      the same specifier for the whole process. app.js captures `document`
      and `window` at module scope, so a second test booting a second jsdom
      would silently keep talking to the FIRST one. Every load appends a
      unique query string to force a fresh module instance.

   2. Globals must exist BEFORE the module body runs. app.js reads
      `document` at import time, so global assignment has to happen first,
      not after. */
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { JSDOM } from 'jsdom';

const V2 = new URL('../../public/v2/', import.meta.url);
const SHELL = readFileSync(new URL('index.html', V2), 'utf8');
let seq = 0;

/** Load a pure v2 module (data.js, render.js) with milestones globals present.
 *  These modules touch no DOM, so no jsdom is needed.
 *
 *  milestones.js is executed in a brand-new `vm.createContext()` sandbox on
 *  every call, rather than `vm.runInThisContext()`. The latter runs
 *  top-level `let`/`const` against Node's real global lexical environment,
 *  which persists for the whole process — a second execution throws
 *  "Identifier '...' has already been declared". A fresh sandbox gets a
 *  fresh lexical environment each time, so redeclaration never happens.
 *
 *  A fresh sandbox's bindings aren't visible from outside the vm: function
 *  declarations land on the sandbox's global object, but `let`/`const`
 *  don't even do that — they only exist inside that one script execution.
 *  So the source is run with an appended epilogue, generated by scanning
 *  milestones.js for its own top-level `function`/`let`/`const` names,
 *  that assigns each one onto the sandbox's globalThis. Those values are
 *  then copied onto the REAL process globalThis, because that's what the
 *  dynamically-imported ES module actually reads through its
 *  `deps = globalThis` default — `import()` always executes in the main
 *  realm, never inside a vm sandbox (see trap #2 above).
 *
 *  These copied globals are deliberately left in place, not restored:
 *  v2/data.js resolves `deps = globalThis` lazily, at call time, not at
 *  import time, so a caller that omits `deps` keeps relying on these
 *  globals for as long as the process runs. bootV2 can safely restore its
 *  window/document swap because app.js captures those references once, at
 *  import time, into closures — that shortcut isn't available here. Each
 *  call overwrites the same fixed set of names with fresh values, so
 *  nothing accumulates. */
export async function loadV2Module(name){
  const milestones = readFileSync(new URL('../../public/milestones.js', import.meta.url), 'utf8');
  const names = new Set();
  for(const m of milestones.matchAll(/^(?:function|let|const)\s+([A-Za-z_$][\w$]*)/gm)){
    names.add(m[1]);
  }
  const epilogue = [...names].map(n => `globalThis.${n} = ${n};`).join('\n');
  const sandbox = {};
  vm.createContext(sandbox);
  vm.runInContext(`${milestones}\n${epilogue}`, sandbox);
  for(const n of names) globalThis[n] = sandbox[n];
  return import(new URL(name, V2) + `?n=${++seq}`);
}

/** Boot the full v2 client against a fresh jsdom.
 *  Returns { dom, window, document, api, errors } where `api` is window.__V2__. */
export async function bootV2({ patients = [], width = 1440, fetchImpl } = {}){
  const dom = new JSDOM(SHELL, { runScripts:'outside-only', url:'http://localhost/v2/' });
  const { window } = dom;
  Object.defineProperty(window, 'innerWidth', { value: width, configurable: true });

  const errors = [];
  window.addEventListener('error', e => errors.push(e.message));
  window.print = () => {};
  window.fetch = fetchImpl
    || (async () => ({ ok:true, json: async () => ({ serverTime:1, patients }) }));

  const milestones = readFileSync(new URL('../../public/milestones.js', import.meta.url), 'utf8');
  window.eval(milestones);

  /* Swap globals via property descriptors, not plain assignment. In
     Node 22, globalThis.navigator is a getter-only accessor
     ({get, set: undefined, configurable: true}); this module runs in
     strict mode (ES modules always do), and a strict-mode plain
     assignment to a getter-only property throws TypeError. Reading the
     original descriptor and writing it back with defineProperty in the
     `finally` preserves whatever shape (accessor or data property) the
     key had before the swap — a property that was an accessor before
     bootV2 ran is an accessor again afterwards, not silently turned into
     a data property. Keys with no prior descriptor (most of this list —
     window/document/KeyboardEvent/etc. don't exist on a plain Node
     globalThis) are deleted on restore instead. If a key's descriptor
     genuinely can't be redefined (non-configurable), the swap for that
     one key is skipped and reported via console.warn rather than
     throwing and aborting the whole boot. */
  const keys = ['window','document','navigator','fetch','KeyboardEvent','MouseEvent','Event','requestAnimationFrame'];
  const prevDescs = {};
  const swapped = [];
  for(const k of keys){
    prevDescs[k] = Object.getOwnPropertyDescriptor(globalThis, k);
    const value = k === 'requestAnimationFrame'
      ? (cb => setTimeout(cb, 0))
      : window[k];
    try {
      Object.defineProperty(globalThis, k, { value, writable: true, enumerable: true, configurable: true });
      swapped.push(k);
    } catch (err) {
      console.warn(`bootV2: could not redefine global "${k}" (${err.message}); leaving it as-is`);
    }
  }

  let api, errCaught;
  try {
    /* The restore must happen AFTER render(), not just after the import.
       app.js resolves document/window/fetch lazily inside its functions
       (not just at module-eval time), so if globals were restored right
       after import — before render() and any subsequent click/keydown
       dispatch — those lookups would hit the real Node globals instead
       of the booted jsdom. Keeping the swap alive across both the import
       AND the render() call, with a single `finally` spanning both, is
       what makes app.js safe to write with bare document/window/fetch
       references inside its functions. */
    await import(new URL('app.js', V2) + `?n=${++seq}`);
    api = window.__V2__;
    if(!api) throw new Error('app.js did not expose window.__V2__');
    /* Await the app's OWN boot render, do not perform it. Calling
       api.render() here is what hid the fact that app.js never booted
       itself in a browser: the harness supplied the missing boot, so the
       whole suite passed against a page that could not start. */
    await api.ready;
  } catch (err) {
    errCaught = err;
  } finally {
    for(const k of swapped){
      const desc = prevDescs[k];
      if(desc === undefined) delete globalThis[k];
      else Object.defineProperty(globalThis, k, desc);
    }
  }
  if(errCaught) throw errCaught;

  return { dom, window, document: window.document, api, errors };
}

/** Dispatch a keydown on the booted document. */
export function press(window, key, mods = {}){
  window.document.dispatchEvent(
    new window.KeyboardEvent('keydown', { key, bubbles:true, ...mods }));
}
